### ISSUE TITLE
Link to tech256 Slack group

### ISSUE THREAD

**Issue by jakesen** [jakesen/nwalsdev#6]
We should provide a link to tech256 so people can join us on Slack!

**Comment by bjkeeton** [comment]
Add it in my last push to my fork. (Will that add to the PR, or do I make a new one?)

**Comment by jakesen** [comment]
Yeah, if you push to a branch that has an open PR, it adds to it. BTW, I invited you to be a collaborator on the main repo...if you accept you will be able to branches and PRs without using a fork 😄

**Comment by jakesen** [comment]
Thanks for adding the Slack link @bjkeeton ! I think I can close this now.
